trigger:
  - <DefineYourTrigger>
stages:
  - stage: Build
    displayName: "Build the App"
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        variables:
          buildConfiguration: "Release"
        steps:
          - script: dotnet build --configuration $(buildConfiguration)
            displayName: "dotnet build $(buildConfiguration)"
          - task: DotNetCoreCLI@2
            inputs:
              command: "publish"
              publishWebProjects: true
              arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"
              publishLocation: "pipeline"

  - stage: Deploy
    displayName: "Deploy to AZ"
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest

        variables:
          buildConfiguration: "Release"
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: "current"
              targetPath: "$(System.DefaultWorkingDirectory)"
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: "AzureRM"
              azureSubscription: "<Enter Service Connection Name>"
              appType: "webApp"
              WebAppName: "<EnterWebAppName>"
              packageForLinux: "$(System.DefaultWorkingDirectory)/**/*.zip"
